global:
  rbac:
    create: true

prometheus:
  namespaceSelector:
    matchNames:
      - redis
      - monitoring
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    scrapeInterval: "15s"
    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: 500m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "gp2"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: false

alertmanager:
  enabled: false